#!/usr/bin/env python3
"""Generate a .mcfunction that builds the Gyroid.

    python3 tools/generate_gyroid_room.py

THE IDEA
A hall full of smooth interwoven walls that curve, twist past each other and never once meet at a
right angle - generated by one line of trigonometry:

    sin(X)cos(Y) + sin(Y)cos(Z) + sin(Z)cos(X) = 0

That is the **gyroid**, a triply-periodic minimal surface. It shows up in butterfly wing scales and
block copolymers, it has no straight lines and no flat regions anywhere, and it is the thing Gemini's
"hyperbolic labyrinth" suggestion was actually pointing at - though at `> 0.7` rather than `= 0`,
which gives disconnected blobs instead of a surface.

Its defining property is the one worth having here: the surface divides space into **two congruent
interpenetrating labyrinths that never connect**. Everything you can see through a gap belongs to a
world you cannot walk to.

THE PROBLEM WITH BUILDING ONE, AND THE FIX
A true gyroid labyrinth is fully three-dimensional. Its passages go up and down as readily as
sideways, so a player without a ladder can reach almost none of it - it is a beautiful space that is
also unplayable.

The fix is to stretch it. `PERIOD_Y` is set several times `PERIOD_XZ`, so the surface completes only
a fraction of a cycle over the height of the room. What was a 3D maze becomes a set of vertical
screens that lean and twist slowly as they rise, standing on a flat floor under a flat ceiling. All
the curvature survives; the unclimbable part does not. Set PERIOD_Y equal to PERIOD_XZ and you get
the real thing, and a room nobody can cross.

THE BREACHES
"Two labyrinths that never connect" is not a description, it is a guarantee, and it means a player
dropped into one of them can reach exactly half the room and no more. The generator's reachability
check caught this on the first run: 22% of the open floor was reachable and 889 cells were sealed on
the far side of a surface with no way through it.

So the surface gets broken. The generator floods the floor from the pale Nexus, finds every region it
cannot reach, and punches a two-block-tall doorway through the single wall cell that would join it -
repeating until the whole floor is one space. Anything still stranded and too small to be worth a
door is filled in solid, so the room contains no sealed pockets at all.

The breaches are the only straight edges in the room, and they should be: the gyroid is a perfect
object, and the way through it is where something has cut.

Because the walls are curved and never parallel, there is no vanishing point and no straight sightline
anywhere in it - you cannot see the far wall from the near one at any angle, which is what makes a
room that is only forty blocks across feel like it has no edge.
"""

import heapq
import math
import os
import random
from collections import deque

WORLD = "run/saves/DimDescentRoomBuilder"
PACK = f"{WORLD}/datapacks/dimdescent_build"
FUNC_DIR = f"{PACK}/data/build/function"
NAME = "gyroid"

BRICK = "dimdescent:altar_stone_bricks"
CRACKED = "dimdescent:cracked_altar_stone_bricks"
VOID = "dimdescent:nullstone"
DARK_BED = "dimdescent:dream_bed"
PALE_BED = "dimdescent:pale_dream_bed"

HALL = 19          # interior half-width -> 39x39 floor
TOP = 21           # interior height

# ---------------------------------------------------------------------------
# THE SURFACE
#
# THICKNESS is the shell either side of the zero level set, and it is the dial that matters: too thin
# and the walls become lace with no mass, too thick and the two labyrinths choke and the floor stops
# being crossable. The reachability check below is what catches the second case.
# ---------------------------------------------------------------------------
PERIOD_XZ = 17.0
PERIOD_Y = 62.0    # >> PERIOD_XZ, so the maze is navigable. See the note above.
THICKNESS = 0.42
PHASE = 0.6        # rotates the pattern so the walls do not line up with the room's own corners

MIN_OPEN = 0.55    # fraction of the floor that must be walkable before any breaching
MAX_BREACH = 60    # doorways cut through the surface to join the two labyrinths
MIN_POCKET = 5     # regions smaller than this are filled in rather than given a door

CRACK_CHANCE = 0.18
random.seed(20260812)


def brick():
    return CRACKED if random.random() < CRACK_CHANCE else BRICK


def gyroid(x, y, z):
    a = 2 * math.pi / PERIOD_XZ
    b = 2 * math.pi / PERIOD_Y
    X, Y, Z = a * x + PHASE, b * y, a * z
    return (math.sin(X) * math.cos(Y)
            + math.sin(Y) * math.cos(Z)
            + math.sin(Z) * math.cos(X))


def main():
    interior = [(x, z) for x in range(-HALL, HALL + 1) for z in range(-HALL, HALL + 1)]
    wall = set()
    for x, z in interior:
        for y in range(1, TOP + 1):
            if abs(gyroid(x + 0.5, y + 0.5, z + 0.5)) < THICKNESS:
                wall.add((x, y, z))

    blocks = {}

    def put(c, block):
        blocks[c] = block

    skin, shell = HALL + 2, HALL + 1
    for x in range(-skin, skin + 1):
        for z in range(-skin, skin + 1):
            for y in range(-2, TOP + 3):
                d = max(abs(x), abs(z))
                if d == skin or y in (-2, TOP + 2):
                    put((x, y, z), VOID)
                elif d == shell or y in (-1, TOP + 1):
                    put((x, y, z), brick())
    for x, z in interior:
        put((x, 0, z), brick())
        put((x, TOP + 1, z), brick())
    # ---- connect the two labyrinths ----------------------------------------
    def open_cells():
        return {c for c in interior
                if (c[0], 1, c[1]) not in wall and (c[0], 2, c[1]) not in wall}

    def flood(start, opens):
        seen, queue = {start}, deque([start])
        while queue:
            x, z = queue.popleft()
            for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                n = (x + dx, z + dz)
                if n in opens and n not in seen:
                    seen.add(n)
                    queue.append(n)
        return seen

    opens = open_cells()
    open_frac = len(opens) / len(interior)
    if open_frac < MIN_OPEN:
        raise AssertionError(
            f"only {open_frac:.0%} of the floor is walkable, under {MIN_OPEN:.0%} - THICKNESS has "
            f"choked the labyrinth. Lower it.")

    def nearest(cells, tx, tz):
        return min(cells, key=lambda c: (c[0] - tx) ** 2 + (c[1] - tz) ** 2)

    pale = nearest(opens, 0, HALL - 3)
    reach = flood(pale, opens)

    # Punch a doorway from the reached region to the nearest stranded one. The wall is two or three
    # cells thick, so removing a SINGLE cell can never join anything - the first attempt did exactly
    # that, failed to connect on its second try, and bulk-filled 649 cells instead. What is needed is
    # the CHEAPEST PATH through the wall: Dijkstra over the floor where crossing open ground is free
    # and cutting a wall cell costs one, then carve whatever it had to cut.
    def carve_to_stranded(opens, reach, stranded):
        seen, prev = {}, {}
        pq = [(0, c) for c in reach]
        heapq.heapify(pq)
        for c in reach:
            seen[c] = 0
        while pq:
            d, c = heapq.heappop(pq)
            if d > seen.get(c, 1 << 30):
                continue
            if c in stranded:
                cut = []
                while c not in reach:
                    if c not in opens:
                        cut.append(c)
                    c = prev[c]
                return cut
            for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                n = (c[0] + dx, c[1] + dz)
                if max(abs(n[0]), abs(n[1])) > HALL - 1:
                    continue
                nd = d + (0 if n in opens else 1)
                if nd < seen.get(n, 1 << 30):
                    seen[n] = nd
                    prev[n] = c
                    heapq.heappush(pq, (nd, n))
        return None

    breaches, carved = 0, 0
    while True:
        stranded = opens - reach
        if not stranded:
            break
        cut = carve_to_stranded(opens, reach, stranded)
        if not cut:
            break
        for c in cut:
            for y in (1, 2):
                wall.discard((c[0], y, c[1]))
            carved += 1
        breaches += 1
        if breaches > MAX_BREACH:
            raise AssertionError(f"needed more than {MAX_BREACH} doorways - the surface is too "
                                 f"closed. Lower THICKNESS.")
        opens = open_cells()
        reach = flood(pale, opens)

    # Anything still stranded is a pocket too small to be worth a door: fill it, so the room has no
    # sealed voids anywhere.
    filled = 0
    for c in opens - reach:
        for y in (1, 2):
            wall.add((c[0], y, c[1]))
        filled += 1

    opens = open_cells()

    for c in wall:
        put(c, brick())

    # ---- checks ------------------------------------------------------------
    solid = set(blocks)
    reach = flood(pale, opens)
    if len(reach) != len(opens):
        raise AssertionError(f"{len(opens) - len(reach)} floor cells still unreachable after "
                             f"{breaches} breaches.")

    dark = nearest(reach, 0, -(HALL - 3))

    def place_bed(cell, facing):
        dz = -1 if facing == "north" else 1
        head = (cell[0], cell[1] + dz)
        if head not in reach:
            raise AssertionError(f"no room for a bed head at {head}.")
        return cell, head

    pale_foot, pale_head = place_bed(pale, "south")
    dark_foot, dark_head = place_bed(dark, "north")
    frac = 1.0

    # ---- emit --------------------------------------------------------------
    shift = 2
    lines = ["# The Gyroid. Stand at the CENTRE of the room, on the ground, in CLEAR AIR, and run:",
             f"#   /function build:{NAME}",
             "# Generated by tools/generate_gyroid_room.py - do not hand-edit.", ""]
    for (x, y, z), block in blocks.items():
        lines.append(f"setblock ~{x} ~{y + shift} ~{z} {block}")
    for block, foot, head, facing in ((PALE_BED, pale_foot, pale_head, "south"),
                                      (DARK_BED, dark_foot, dark_head, "north")):
        lines.append(f"setblock ~{foot[0]} ~{1 + shift} ~{foot[1]} "
                     f"{block}[facing={facing},part=foot]")
        lines.append(f"setblock ~{head[0]} ~{1 + shift} ~{head[1]} "
                     f"{block}[facing={facing},part=head]")

    os.makedirs(FUNC_DIR, exist_ok=True)
    with open(f"{PACK}/pack.mcmeta", "w") as f:
        f.write('{\n  "pack": {\n    "pack_format": 48,\n'
                '    "description": "dim_descent build helpers"\n  }\n}\n')
    with open(f"{FUNC_DIR}/{NAME}.mcfunction", "w") as f:
        f.write("\n".join(lines) + "\n")

    span_xz, span_y = 2 * skin + 1, TOP + 5
    print(f"wrote {FUNC_DIR}/{NAME}.mcfunction")
    print(f"  {len(lines) - 4} setblock commands, {len(wall)} blocks of surface")
    print(f"  period {PERIOD_XZ:.0f} across, {PERIOD_Y:.0f} vertical "
          f"({PERIOD_Y / PERIOD_XZ:.1f}x stretch - that is what makes it walkable)")
    print(f"  floor {open_frac:.0%} open; {breaches} doorways cut ({carved} blocks removed), "
          f"{filled} cells of dead pocket filled")
    print(f"  every open floor cell now reachable from the pale Nexus ({len(reach)} of them)")
    print(f"  pale Nexus at {pale_foot}, dark at {dark_foot}")
    print(f"  capture size {span_xz} x {span_y} x {span_xz} "
          f"({'OK' if max(span_xz, span_y) <= 48 else 'TOO BIG'} for the 48 cap)")
    print()
    print("  structure blocks, relative to the room CENTRE P:")
    print(f"    SAVE   corner at  P + ({-skin - 1}, -1, {-skin - 1})")
    print(f"    CORNER corner at  P + ({skin + 1}, {span_y}, {skin + 1})")


if __name__ == "__main__":
    main()
